apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hootlet
  name: hootlet
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
        run: hootlet
    spec:
      containers:
      - image: tehut/hootlet:latest
        imagePullPolicy: Always
        name: hootlet
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-15T21:21:49Z
    lastUpdateTime: 2017-08-15T21:21:49Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1